### PR TITLE
Support PHP8.0

### PR DESCRIPTION
**Pull request by limingxinleo**

### CODE REVIEW

**Comment by jcchavezs** [comment]
We just merged support for it in https://github.com/openzipkin/zipkin-php/commit/b179cc11ddb30b6368106369d8f259189f2ca6d8. Notice we are aiming to release Zipkin 3.0 for such purpose as we failed to keep current compatibility 7.1+ with 8.0 in some important libraries (see https://github.com/openzipkin/zipkin-php/issues/202#issuecomment-849155559).

**Comment by limingxinleo** [comment]
Could you please send me a email when support php8?

Thanks very much

**Comment by limingxinleo** [comment]
Could you please take a look at this

**Comment by jcchavezs** [comment]
Hi I just came back from PTO due to family reasons. I will look into this next week.

**Comment by limingxinleo** [comment]
Thanks

**Comment by leocarmo** [comment]
@jcchavezs merge please?

**Comment by jcchavezs** [comment]
I will merge this, tho 9.0 is failling we can tackle that in a next PR.

**Pull request merged**
