### PR TITLE
fix: exceptions may not be raised when using noop span.

### PR DESCRIPTION
**Pull request by Reasno**

### CODE REVIEW

**Comment by jcchavezs** [comment]
Hi there!

Thanks for opening this. Actually the error is that we are returning a noop
context when the span is noop and that is incorrect because although span
is noop you don't want to break propagation. I am finishing unit tests for
a PR on this.

**Comment by jcchavezs** [comment]
First PR to solve this issue:
https://github.com/openzipkin/zipkin-php/pull/146

José Carlos Chávez


man. 18. mai 2020 kl. 13:10 skrev José Carlos Chávez <jcchavezs@gmail.com>:

> Hi there!
>
> Thanks for opening this. Actually the error is that we are returning a
> noop context when the span is noop and that is incorrect because although
> span is noop you don't want to break propagation. I am finishing unit tests
> for a PR on this.
>

**Comment by jcchavezs** [comment]
Thanks for this @reasno. I just opened a PR replacing this one. Main reason
for not going with this PR is because this change breaks the context
propagation to downstreams when in a noop span and that is not desirable.
If there is a noop (meaning unsampled) we still want to propagate the
tracing context to avoid upstream to start traces by themselves and honour
the service starting the trace.

**Comment by Reasno** [comment]
Great. I am closing this one

**Pull request closed without merging**
