### PR TITLE
Fixed bug that typed property $scope must not be accessed before initialization.

### PR DESCRIPTION
**Pull request by limingxinleo**

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thank you. Do you mind adding a unit test to cover this?

**Comment by limingxinleo** [comment]
@jcchavezs I already added the test case about this pr.

Please try review it again.

**Comment by limingxinleo** [comment]
fix https://github.com/hyperf/tracer/issues/9

**Comment by diankemao** [comment]
bash-5.1# php -v
PHP 8.0.12 (cli) (built: Oct 21 2021 16:35:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
    
    

bash-5.1# php bin/hyperf.php start
[INFO] Process[metric.0] start.
[INFO] Worker#1 started.
[INFO] Process[queue.default.0] start.
[INFO] Process[Consumer-hyperf.0] start.
[INFO] Worker#0 started.
[INFO] HTTP Server listening at 0.0.0.0:9511
[ERROR] Typed property ZipkinOpenTracing\Span::$scope must not be accessed before initialization[66] in /data/website/vendor/jcchavezs/zipkin-opentracing/src/ZipkinOpenTracing/Span.php
[ERROR] #0 /data/website/vendor/hyperf/tracer/src/Middleware/TraceMiddleware.php(78): ZipkinOpenTracing\Span->finish()
#1 /data/website/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Tracer\Middleware\TraceMiddleware->process()
#2 /data/website/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#3 /data/website/vendor/hyperf/metric/src/Middleware/MetricMiddleware.php(37): Hyperf\Dispatcher\HttpRequestHandler->handle()
#4 /data/website/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Metric\Middleware\MetricMiddleware->process()
#5 /data/website/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#6 /data/website/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle()
#7 /data/website/vendor/hyperf/http-server/src/Server.php(116): Hyperf\Dispatcher\HttpDispatcher->dispatch()
#8 {main}
[ERROR] Typed property ZipkinOpenTracing\Span::$scope must not be accessed before initialization[66] in /data/website/vendor/jcchavezs/zipkin-opentracing/src/ZipkinOpenTracing/Span.php
[ERROR] #0 /data/website/vendor/hyperf/tracer/src/Middleware/TraceMiddleware.php(78): ZipkinOpenTracing\Span->finish()
#1 /data/website/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Tracer\Middleware\TraceMiddleware->process()
#2 /data/website/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#3 /data/website/vendor/hyperf/metric/src/Middleware/MetricMiddleware.php(37): Hyperf\Dispatcher\HttpRequestHandler->handle()
#4 /data/website/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Metric\Middleware\MetricMiddleware->process()
#5 /data/website/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#6 /data/website/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle()
#7 /data/website/vendor/hyperf/http-server/src/Server.php(116): Hyperf\Dispatcher\HttpDispatcher->dispatch()
#8 {main}

**Comment by limingxinleo** [comment]
Hi

When will the fixed version be released?

**Comment by jcchavezs** [comment]
I just released it
https://github.com/jcchavezs/zipkin-php-opentracing/tree/2.0.1

José Carlos Chávez


man. 22. nov. 2021 kl. 10:40 skrev 李铭昕 ***@***.***>:

**Pull request merged**
