### PR TITLE
Added check for ignore_active_span option when starting a span

### PR DESCRIPTION
**Pull request by person-unko**
Related to issue https://github.com/jcchavezs/zipkin-php-opentracing/issues/66#issue-1959511533

### CODE REVIEW

**Comment by jcchavezs** [comment]
Could you please cover this with a uni test?

**Comment by person-unko** [comment]
added 👍

**Review by jcchavezs — APPROVED** [review]

**Comment by jcchavezs** [comment]
Do you mind fixing the failing tests?

**Comment by person-unko** [comment]
Added the missing return types in request class. Should fix it

**Comment by person-unko** [comment]
Should now work I think

**Comment by jcchavezs** [comment]
Thanks!

**Pull request merged**
