### PR TITLE
Use OT Span setTag() calls instead of zipkin tag() on Tracer::startSpan()

### PR DESCRIPTION
**Pull request by eligijusvitkauskas-home24**
Previous fix for casting tag value to string only works for setTag() method calls. Problem is still present on startSpan() call.

### CODE REVIEW

**Comment by jcchavezs** [comment]
@eligijusvitkauskas-home24  can you please rebase this so we can include it in the release `0.1.1`?

**Review by jcchavezs — APPROVED** [review]

**Comment by eligijusvitkauskas-home24** [comment]
Done

**Comment by jcchavezs** [comment]
@eligijusvitkauskas-home24 btw I invited you to the repo: https://github.com/jcchavezs/zipkin-php-opentracing/invitations

**Comment by jcchavezs** [comment]
This is green, surprisingly it does trigger the confirmation: https://travis-ci.org/jcchavezs/zipkin-php-opentracing

**Pull request merged**
